// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQsvtTqjZdBvtZFJs5I9vfEKJAsRnPiWc',
    appId: '1:613818944989:web:3625ea16bb0a2a3fc73a34',
    messagingSenderId: '613818944989',
    projectId: 'note-app-770c1',
    authDomain: 'note-app-770c1.firebaseapp.com',
    storageBucket: 'note-app-770c1.firebasestorage.app',
    measurementId: 'G-BNCH8905DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdoX-rSVGNKuQSmd_HAkUF15JbL5oWcg',
    appId: '1:613818944989:android:ee97b03c1db53a29c73a34',
    messagingSenderId: '613818944989',
    projectId: 'note-app-770c1',
    storageBucket: 'note-app-770c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Fe8TUV8IKJ-zTddGQQ6-xF2iXxvrXo4',
    appId: '1:613818944989:ios:332833a37d237ebac73a34',
    messagingSenderId: '613818944989',
    projectId: 'note-app-770c1',
    storageBucket: 'note-app-770c1.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Fe8TUV8IKJ-zTddGQQ6-xF2iXxvrXo4',
    appId: '1:613818944989:ios:332833a37d237ebac73a34',
    messagingSenderId: '613818944989',
    projectId: 'note-app-770c1',
    storageBucket: 'note-app-770c1.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQsvtTqjZdBvtZFJs5I9vfEKJAsRnPiWc',
    appId: '1:613818944989:web:d6f4de5af3b8b4d7c73a34',
    messagingSenderId: '613818944989',
    projectId: 'note-app-770c1',
    authDomain: 'note-app-770c1.firebaseapp.com',
    storageBucket: 'note-app-770c1.firebasestorage.app',
    measurementId: 'G-EXYRMQD27E',
  );
}
